function hi(){
       var  name=document.getElementById("name").Value;
       var  phone=document.getElementById("phone").Value;
       var  address=document.getElementById("address").Value;
       var  mail=document.getElementById("email").Value;
       var  thing=document.getElementById("thing").Value;

    alert ("your name is "+name+" your phone number is "+phone+" and the thing you ordered is to be dilevered to "+address+" if their will be any problem we will mail you at your email address "+mail+" thing you ordered is "+thing );
             }    
